name: hexalpha
favicon: null
layout_spectrum: 0
typography_spectrum: 0.89265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191a19'
    - '#434343'
    - '#809292'
    - '#666666'
    - '#ffffff'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
