name: hexalpha
favicon: null
layout_spectrum: 0.3657758696936071
typography_spectrum: 0.9457636307924986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.0633565098978579
  lightness: 0.5416996509302408
  saturation: 0.6342523351777345
  rhythmicContrast: 0.6193037226330489
purpose: []
